; PlatformIO Project Configuration File
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform  = espressif32
board     = esp32dev
framework = arduino

; Monitor serie
monitor_speed = 115200

; Librerías del proyecto
lib_deps =
  bogde/HX711
  adafruit/Adafruit GFX Library
  adafruit/Adafruit SSD1306
  knolleary/PubSubClient
  bblanchon/ArduinoJson